### ISSUE TITLE
New Discord ?

### ISSUE THREAD

**Issue by AdnanCukur** [NecronomiconCoding/Pokemon-Go-Bot#1]
Should we get a new discord for this ?

**Comment by Nexusphobiker** [comment]
im defnitly up for that

**Comment by NecronomiconCoding** [comment]
still not sure

**Comment by Bitsnoxx** [comment]
Xivia created one over here https://discord.gg/CWFRh

**Comment by linkz-db** [comment]
Would be nice if the instant invite would last longer xD
