### ISSUE TITLE
Best CP not displying correctly.

### ISSUE THREAD

**Issue by NumberXer0** [NecronomiconCoding/Pokemon-Go-Bot#101]
When it transfers a Pokemon, the area for best CP is a ridiculously long number like 9965100841343455963. 

For example: [19:10:09] (TRANSFERED) Rhyhorn with 348 (68.33 % perfect) CP (Best: 9965100841343455963 | (91.67       % perfect))

Is this correct? It looks like that number should be the CP. If it isn't, care to explain what the numbers mean?

**Comment by Shroomzie** [comment]
I believe you are on a old build. Clone the repos and build again. it was fixed about 10 commits ago

https://github.com/NecronomiconCoding/Pokemon-Go-Bot/commit/55ae91a5b3a96f109343a827adda79a1042453f9

**Comment by NumberXer0** [comment]
That would be the case. I downloaded the newest build this morning before work, I didn't even check for an update. My fault haha. Issue resolved.

**Comment by Shroomzie** [comment]
It messed with my OCD thats for sure.
