### ISSUE TITLE
(ERROR) NullReferenceException - Restarting

### ISSUE THREAD

**Issue by Naprosnia** [NecronomiconCoding/Pokemon-Go-Bot#103]
when start, im getting this error.

[00:16:11] (INFO) Loading File: Configs\ConfigPokemonsToKeep.txt
[00:16:11] (ERROR) NullReferenceException - Restarting

**Comment by gewoon** [comment]
I haven't used the PokemonsToKeep function yet but have you listed the pokemon in the right order? I mean like seperate the Pokemon with an "Enter" or ','.

**Comment by NecronomiconCoding** [comment]
thats an old version.

**Comment by Naprosnia** [comment]
ok, updating and try again
