### ISSUE TITLE
Unactivated ptc accounts gets PtcOfflineException after 48 hours. 

### ISSUE THREAD

**Issue by Einarloe** [NecronomiconCoding/Pokemon-Go-Bot#108]
Just a heads up, as many of you might get the same error due to the site always being too overworked to activate them. 

The console will say ptc is offline, nox gets a wierd error and gets stuck.
I confirmed the issue when trying to log in on my phone, which tells me to activate the account. 

Not an issue with the bot itself, but figured it might become a problem for others aswell.

**Comment by lauw** [comment]
This is probably due to the latest change where it triggers PTCOfflineException for every Internal Server Error.
To correctly fix this will need a non-activated account though.
