### ISSUE TITLE
Reading file from disk

### ISSUE THREAD

**Issue by Shoua** [NecronomiconCoding/Pokemon-Go-Bot#124]
Directory.GetCurrentDirectory()  wont point to the right path if executed from a bat file.  It should probably be Application.StartupPath instead.

**Comment by shejk0** [comment]
You are starting batch from e.g. your desktop, this way it wants to read files from it.

Just use this instead:
cd C:\Users\user\Desktop\BOT
start "1" PokemonGo.RocketAPI.Console.exe
