### ISSUE TITLE
Circulare Nav needs improvment

### ISSUE THREAD

**Issue by OuttaControlX** [NecronomiconCoding/Pokemon-Go-Bot#2]
Just before ferox repo went offline we were discussing how it misses pokestops and needs 5mins to get improved.

**Comment by NecronomiconCoding** [comment]
Didn't notice what happened, any infos ?

**Comment by Zeromark30** [comment]
Someone who was leaving for the weekend added a pull for  some code to map out the best route of the nearest 10 pokestops and do a best fit test to hit them all or something close I believe.

**Comment by Zeromark30** [comment]
https://webcache.googleusercontent.com/search?q=cache:P2hOT00wiIIJ:https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pulls+&cd=1&hl=en&ct=clnk&gl=us found it. hardwell Efficient path generation to prevent large jumps.

**Comment by kevvv** [comment]
Would be nice if there was a feature to map the smallest route on all the stops.

**Comment by Nyankoo** [comment]
Whats the difference between this and the human walking that's already implemented?

**Comment by OuttaControlX** [comment]
no see im using hardells path gen, but literally minutes before the repo was pulled he and others wereb discussing how it needed further improvident and coulkd be done in a few minutes, anyone in contact with him?

**Comment by mrnitrate** [comment]
yea he mentioned in discord that it found the shortest path correctly it just did not pick the closest pokestop from your starting lat and long to use first.  after the first stop everything is optimal.

**Comment by OuttaControlX** [comment]
Ah ok no big deal then,  his path gen is much better than the one given,  i get 15k more  xp/hr using hardells circular pathing,  big improvement.

**Comment by Nyankoo** [comment]
@OuttaControlX At what km/h?
