### ISSUE TITLE
not work catch, gym, pokestop, nothing. only dipslay name pokemon

### ISSUE THREAD

**Issue by n3o999** [NecronomiconCoding/Pokemon-Go-Bot#228]
Not work this version. can you do an txt for explain user.setting step by step? thanks

**Comment by pattythesleeper** [comment]
@n3o999 it works perfectly for me.

 its pretty easy to use.

**Comment by iamD2** [comment]
you most likely got soft banned, just wait 4 hours

**Comment by goldxero** [comment]
softban confirmed, just wait it out

**Comment by n3o999** [comment]
no. nothing soft ban. pc crazy. i delete all. clean pc and file. insert a new correct coord and work perfectly again :dancer:
