### ISSUE TITLE
Tranfer Pokemon thats in a gym

### ISSUE THREAD

**Issue by schadis** [NecronomiconCoding/Pokemon-Go-Bot#24]
bot whants to transfer my Pidgeot with 718 cp but cant cause its in a gym.
i have a better one with over 1300 in my bag that causes tha problem

**Comment by ReddoKiddo** [comment]
You sure you're on latest build? it shouldn't be doing this... refer to "Inventory.cs" line 27

` var pokemonList = myPokemon.Where(p => p.DeployedFortId == 0).ToList(); //Don't evolve pokemon in gyms`

**Comment by schadis** [comment]
have updated again and it still ties to transfer my pokemont that is in the gym,
maybe cause i set that all under 800 can be sent and it is a 718???
that those 2 functions dont work correct together?

**Comment by ReddoKiddo** [comment]
No, looking from the code it should work together. First it removes pokemon that are in gym then it removes pokemon that are in favorite list and after that it sends list to the actual transfer and in transfer function it check for minIV and minCP...

everything should work

**Comment by schadis** [comment]
Tried Spegeli gith ...his doesnt doch that... why Arena you Not working toghether?

**Comment by schadis** [comment]
Fucking smartphone autocorrection

**Comment by ReddoKiddo** [comment]
I can't reproduce what you're saying.... I also have another person trying to reproduce this

he put hypno in gym set the minCP on 1000 (hypno was mid  800) and started bot, it did not transfer hypno
