### ISSUE TITLE
I keep getting this error what should i do

### ISSUE THREAD

**Issue by AKhozim** [NecronomiconCoding/Pokemon-Go-Bot#244]
![image](https://cloud.githubusercontent.com/assets/11014304/17079282/b94e8dbc-513d-11e6-9410-0e7c03a49eb2.png)
 please help

**Comment by Zashuiba** [comment]
you need to set the startup project on "poke.........CONSOLE" in visual stududio, not poke.,....API

**Comment by Antidote78** [comment]
Click on projet in the top menu and click on define as startup project or something like that (should be close, sorry dont know it in english"

**Comment by ghsi10** [comment]
you try to run API.
you should run console.

**Comment by onlylove943** [comment]
No. You should read the README.md

**Comment by AKhozim** [comment]
problem solved guys 
i changed it to console application and found only 1 errors "google.protobuf could not be found visual studio"
so i google the error and i found this http://stackoverflow.com/questions/32049731/google-protobuf-3-0-0-assemblies-for-c-sharp 
it tells me to install the google.protobuf via nuget console in visual studio
