### ISSUE TITLE
Transfer enhancement 

### ISSUE THREAD

**Issue by BahaStriker** [NecronomiconCoding/Pokemon-Go-Bot#3]
can you make it so it can transfer duplicate lower than a specified CP? Because I don't really want to transfer all my duplicates

**Comment by Zeromark30** [comment]
Just use the cp threshold option.

**Comment by BahaStriker** [comment]
But that will transfer all Pokemons below a certain CP, I just want to transfer duplicates and not all of them

**Comment by Luc4z** [comment]
you have to do it yourself , add // before transferall

**Comment by BahaStriker** [comment]
alright thanks c:
