### ISSUE TITLE
[BUG] Most pokemon FLEE

### ISSUE THREAD

**Issue by deknarf** [NecronomiconCoding/Pokemon-Go-Bot#31]
What happened?

Some versions ago, before the walking and recycling, pokemon were being catched a LOT more than they are now.

90% flees now.

**Comment by MonsterMMORPG** [comment]
it is not bug u are soft banned

**Comment by roflinger** [comment]
Softbanned would all flee not 90% .. i was soft banned a hour ago

**Comment by deknarf** [comment]
roflinger is right. softban would flee 100% and not get anything from pokestops.
I receive items and exp from pokestops, but almost all pokemon flee
