### ISSUE TITLE
Better Colors

### ISSUE THREAD

**Issue by roflinger** [NecronomiconCoding/Pokemon-Go-Bot#32]
hey,

i do it like this
`  switch (level)
            {
                case LogLevel.Error:
                    System.Console.ForegroundColor = color != ConsoleColor.Black ? color : ConsoleColor.Red;
                    System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] {message}");
                    break;
                case LogLevel.Warning:
                    System.Console.ForegroundColor = color != ConsoleColor.Black ? color : ConsoleColor.Yellow;
                    System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] (WARNING) {message}");
                    break;
                case LogLevel.Info:
                    System.Console.ForegroundColor = color != ConsoleColor.Black ? color : ConsoleColor.Gray;
                    System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] (INFO) {message}");
                    break;
                case LogLevel.Debug:
                    System.Console.ForegroundColor = color != ConsoleColor.Black ? color : ConsoleColor.Gray;
                    System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] (DEBUG) {message}");
                    break;
                case LogLevel.None:
                    System.Console.ForegroundColor = color != ConsoleColor.Black ? color : ConsoleColor.White;
                    System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] (ERROR) {message}");
                    break;
                default:
                    System.Console.ForegroundColor = color != ConsoleColor.Black ? color : ConsoleColor.White;
                    System.Console.WriteLine($"[{DateTime.Now.ToString("HH:mm:ss")}] (ERROR) {message}");
                    break;
            }`

you could also set a Loglevel.no with no text, and do:

 $"(TRANSFER) {duplicatePokemon.PokemonId} with {duplicatePokemon.Cp} CP (Best: {bestPokemonOfType})",
                    LogLevel.no, ConsoleColor.DarkGreen);

it avoids the double info (INFO) (CATCH), (INFO) (RECYCLE) and so on

greets

**Comment by TheCrimsonDevil** [comment]
What did your last issue to Ferox's github say?

https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/310 (drop this in google for a cache link)
"devs are fuckers"

I noticed right after that, the github dissappeared.

**Comment by roflinger** [comment]
yep because they changed my title to "i am a fucker" ;)

**Comment by TheCrimsonDevil** [comment]
Wait, was it a legitimate issue they just didn't feel like solving, so they changed the title to "I am a fucker" (talking about you)? If so... I'm glad the project was moved to someone else's hands.

**Comment by roflinger** [comment]
don´t remember what i wrote but i think i was not nice tbh .. but didn´t call anybody like a fucker ..

and yes i am also happy that it moved

**Comment by Bogenschuetze** [comment]
What exactly happened? this is the new git now?
