### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by crack00r** [NecronomiconCoding/Pokemon-Go-Bot#35]
[21:05:12] (INFO) (RECYCLE) 1x ItemPokeBall
[21:06:16] (INFO) (POKESTOP): Het Behouden Huys in 903m distance
[21:06:16] (INFO) (POKESTOP) XP: 50, Gems: 0, Eggs:  Items: 4 x ItemPokeBall
[21:06:17] (INFO) (RECYCLE) 4x ItemPokeBall
[21:06:19] (INFO) (CATCH) Weedle with CP 185 (31,67% perfect) and CaptureProbability: 0,343478 using a ITEM_POKE_BALL in 84m distance
[21:06:37] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Eine Ausnahme vom Typ "PokemonGo.RocketAPI.Exceptions.InvalidResponseException" wurde ausgelöst.
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Manuel\Desktop\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:Zeile 39.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Manuel\Desktop\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:Zeile 183.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Inventory.<GetPokemons>d__9.MoveNext() in C:\Users\Manuel\Desktop\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:Zeile 132.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__2.MoveNext() in C:\Users\Manuel\Desktop\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Inventory.cs:Zeile 25.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<TransferDuplicatePokemon>d__16.MoveNext() in C:\Users\Manuel\Desktop\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 323.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__11.MoveNext() in C:\Users\Manuel\Desktop\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 227.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__13.MoveNext() in C:\Users\Manuel\Desktop\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 278.
[21:06:47] (ERROR) Exception: PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Eine Ausnahme vom Typ "PokemonGo.RocketAPI.Exceptions.InvalidResponseException" wurde ausgelöst.
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Manuel\Desktop\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:Zeile 39.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

**Comment by NecronomiconCoding** [comment]
known error , thanks
