### ISSUE TITLE
Values?

### ISSUE THREAD

**Issue by biiq** [NecronomiconCoding/Pokemon-Go-Bot#36]
I apologize if I shall seem silly , but I really do not understand the meaning of the values ​​of "KeepMinIVPercentage" and "KeepMinCP". That depends on them and what values ​​to enter ? Sincerely.

**Comment by shejk0** [comment]
I see it that way, will keep your Pokemon if IV (Individual Value) is higher or equal to your "X" AND has CP at least your "X".

**Comment by Sylencer90** [comment]
Leave IV at default and i personally use cp at 600, depends on preferences. The CP means, it will transfer pokemon under the X amount (600 for me). Like 599 weedle will get transferred, 600 not. Got it?

**Comment by BioMuell** [comment]
Well, R.I.P all Magikarps?
