### ISSUE TITLE
Pokemon Blacklist/Whitelist

### ISSUE THREAD

**Issue by qaqsd123** [NecronomiconCoding/Pokemon-Go-Bot#41]
Is it possible to make it so that it doesn't catch certain Pokemon, or only catches certain Pokemon?

**Comment by Sylencer90** [comment]
Yeah i'd like to have such a feature too but with transferring, i would like to keep the evolve slaves like pidgey/weedle and such like 60 times and throw other like zubat away.

**Comment by NecronomiconCoding** [comment]
https://github.com/NecronomiconCoding/Pokemon-Go-Bot/commit/b3acc482ab13522047a8798dbb32df222b488723
