### ISSUE TITLE
[REQUEST] Use lucky eggs if available

### ISSUE THREAD

**Issue by gewoon** [NecronomiconCoding/Pokemon-Go-Bot#48]
I got 4 Lucky Eggs doing nothing, maybe the bot can use them to speed up leveling.

**Comment by deknarf** [comment]
That would be a nice addition for in like version 1.1 / 1.2 or something.
 (btw. shout out naar de Nederlander)

**Comment by Hitsuomy** [comment]
Would be nice to have, but I think if implemented this needs to be optional, don't want to use my Lucky Eggs for now.

**Comment by gewoon** [comment]
Yes that was what i meant, Hitsuomy.

**Comment by Zverbeek** [comment]
Egg usage would be nice, I'll look into it.

**Comment by gewoon** [comment]
Thanks.
