### ISSUE TITLE
[REQUEST] Show % perfect when transferring

### ISSUE THREAD

**Issue by LasaFawkes** [NecronomiconCoding/Pokemon-Go-Bot#55]
For instance:
(TRANSFERRED) Growlithe with 162 CP (x% perfect) (Best: 682 | x% perfect)

Also, I noticed there are at least two pokémon names misspelled: "Charmender" instead of Charmander, and "Clefary" instead of Clefairy. Thank you <3

**Comment by deknarf** [comment]
I will work on some textual changes so Necro can focus on things more important.

**Comment by deknarf** [comment]
I suggested 2 filechanges. Now we wait :+1:

**Comment by navidemad** [comment]
Done
#57

**Comment by deknarf** [comment]
Awesome
