### ISSUE TITLE
List Pokemon to evolve not working

### ISSUE THREAD

**Issue by eLyiN** [NecronomiconCoding/Pokemon-Go-Bot#62]
Just tried again, a "Squirtle"  has evolved. Obviously not listed.

**Comment by ReddoKiddo** [comment]
It is working... just tested this|

proof: http://imgur.com/a/3aMzE

**Comment by eLyiN** [comment]
Is working In the lastest update, when i just created the issue was not working, because it has 2 pokemons that wasn't in the list.

But great work anyway, hopefully works for next time!
