### ISSUE TITLE
Perfection %'s are negative

### ISSUE THREAD

**Issue by Brewfasa** [NecronomiconCoding/Pokemon-Go-Bot#63]
The perfection in the console are shown the other way around, I just encountered a 10 cp magikarp which was according to the console a 85% perfection for a level 26. When i find a really high cp pokemon, the perfection is shown as low..

https://i.gyazo.com/b0b27f50f178885eac853532bd64e643.png

**Comment by Hitsuomy** [comment]
The perfection is not about the CP is about the IVs
