### ISSUE TITLE
26 Errors when trying to build solution.

### ISSUE THREAD

**Issue by RZeroFrost** [NecronomiconCoding/Pokemon-Go-Bot#65]
downloaded, tried to build without modifying settings, 26 errors.

**Comment by Hitsuomy** [comment]
Post changelog pls.

**Comment by RZeroFrost** [comment]
http://imgur.com/a/pZLAO

**Comment by RZeroFrost** [comment]
No thing changed, literally just downloaded and tried to ctrl+F5 as the readme said.

**Comment by RZeroFrost** [comment]
Now, gives me this 
http://imgur.com/a/4krgC

**Comment by Hitsuomy** [comment]
Try the latest build, tested here now, working:
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by Hitsuomy** [comment]
Didn't change a thing here, just made the download and the build. Working normally.

**Comment by RZeroFrost** [comment]
Still doesnt work: gives this:
http://imgur.com/a/4krgC

**Comment by septemus** [comment]
Click on "Solution ' Pokemon Go Rocket API' (3 projects)" and then press Alt+Enter. Change the "Single Startup Project" to the project with ".Console". Should work now. If you built it before, close your currently running bot.

**Comment by RZeroFrost** [comment]
It cant find google.protobuff or the .dll's associated with project.

**Comment by Shroomzie** [comment]
Its because he/she is trying to build PokemonGo.RocketApi instead of setting "Setup as startup project" on PokemonGo.RocketApi.Console like they prolly should have!?

**Comment by septemus** [comment]
@RZeroFrost Look at my earlier post.

**Comment by RZeroFrost** [comment]
I did SET it as the startup project.
ctrl+F5 tries to fetch nuget data, fails on google.protobuff

**Comment by Shroomzie** [comment]
Sounds like a issue with your build environment and not this repository!?
