### ISSUE TITLE
[Minor] Character Status Order not Correct

### ISSUE THREAD

**Issue by problemz** [NecronomiconCoding/Pokemon-Go-Bot#69]
![image](https://cloud.githubusercontent.com/assets/20581518/17071715/974f326e-5063-11e6-9fed-fd54099533a9.png)

... Level [Trainername] [#]

Edit: Also at the beginning
![image](https://cloud.githubusercontent.com/assets/20581518/17071857/7c4feb60-5064-11e6-87d0-dd601aa3a850.png)

**Comment by LasaFawkes** [comment]
I was about to suggest the same thing. It would also be awesome if the title could state the info more clearly and with the current amount of stardust, something like:
CharacterName | Level X - (CurrentExp/TotalExp XP) | Stardust XXXXXX

**Comment by NecronomiconCoding** [comment]
done.
