### ISSUE TITLE
Scanning nearby Pokestops, constant scanning pokemon while 'walking'

### ISSUE THREAD

**Issue by Ecalite** [NecronomiconCoding/Pokemon-Go-Bot#7]
Hello Necro, incase my post in the forums got scrolled away by the flood.. I will post it here

I have a few issues with the bot that I've noticed, and I was wondering if this was an intended feature or just something of a coding limitation. 

#1 - The bot doesn't activate the other pokestops within 'clicking' range of the intended pokestop. It's like as if it's really single minded towards the target pokestop and doesn't 'scan' the area of the pokestop. Most pokestops in this game are almost always accompanied by another one, or two (maybe even 3 to 4) additional pokestops if we are choosing locations like Melbourne, Sydney, or New York. I feel this is a massive loss of EXP and it also make it look 'unnatural'. So perhaps create a 'scan' function when we arrive at a pokestop to look for other pokestops in-range without having to move.

#2 - With walking implemented, I think that always scanning for pokemons en-route to another pokestop should be implemented. I understand how this wasn't a priority before as we are technically teleporting around pokestops and just catching whatever pokemon that is around there before teleporting away again. This will make the bot look less 'unnatural' and it will also increase our EXP gain as we are already passing through by 'walking around' anyways

Please consider the above 2 points as I believe this will exponentially increase our EXP and coincidentally make our bot look more human-like

Thank you in advance!

**Comment by Mavmins** [comment]
Great ideas. There was a pull request on the old one to sort stops by distance so maybe that would help but I didn't save it

**Comment by MonsterMMORPG** [comment]
i support both

**Comment by AdnanCukur** [comment]
A Shortest distance algorithm to sort the pokestops before starting the bot, should fix this, there was a pull request on ferox git for this, but it had some flaws.

**Comment by Hidan123** [comment]
Good idea :+1:

**Comment by mczee** [comment]
The biggest addition would be to click PokeStops and catch Pokemon that are in click range while walking mode to next coords is active. As soon as that is implemented we can add a GPX parser and handle complete gps routes through the city.

**Comment by Ecalite** [comment]
So... apparently someone already coded a 'catch pokemon while walking' based off ferox's bot before it went down

"Evolve fix + Catch Pokemon while walking to the next location
Based on the last version of FeroxRev's bot, including walking to locations.
https://mega.nz/#!qJkBHIba!pmc7ndQwY...s7JsPO5xRwME7A"

From the forums.. done by Maclone..

**Comment by mczee** [comment]
Necro just added it to this one too.

Now we can go ahead and add a GPX parser and route handler to let the bot run realistic routes through the city.

**Comment by joshk6656** [comment]
wasn't number 2 fixed by this commit?

https://github.com/NecronomiconCoding/Pokemon-Go-Bot/commit/09faff8ebcd43840df484e0cc1c847bf2a8eabcf
