### ISSUE TITLE
[REQUEST] updateTitle, Put updating values to the Begin of title string

### ISSUE THREAD

**Issue by salvaracer** [NecronomiconCoding/Pokemon-Go-Bot#73]
It would be a nicer UX if you can see **directly** the updating XP values in the taskbar :+1: 

And maybe something like
* $"LVL: ({currentExp}/({maxExp}/100))% to {nextlevel} - {playname} {currentlevel}"
* $"{playername} {currentlevel} (({currentExp}/({maxExp}/100))% -> {nextlevel})"

#64 
#38

**Comment by gewoon** [comment]
Yep i'd like this too, $"{playername} {currentlevel} (({currentExp}/({maxExp}/100))% -> {nextlevel})" and updating XP.

**Comment by Brewfasa** [comment]
And maybe something like the ammount of Experience you're getting per hour xp p/h and maybe pokemons caught p/h

**Comment by gewoon** [comment]
That's a very good idea too, kind of an estimate of how much you're earning per hour.

**Comment by salvaracer** [comment]
I would prefera percentage number of level progress in the title string 8)
