### ISSUE TITLE
[Minor] XP values don't match with the actual game ones

### ISSUE THREAD

**Issue by LasaFawkes** [NecronomiconCoding/Pokemon-Go-Bot#77]
I'm at level 22 and it should display 100.000 XP as the maximum but it shows 175.000 in the console.

Here's a list with the XP requirements for all the levels currently available in the game: https://www.reddit.com/r/TheSilphRoad/comments/4s1cpq/xp_requirements_for_levels_so_far_125/

**Comment by Jaerin** [comment]
It actually currently shows your current total xp/total cumulative xp needed for the next level.  So there will be a 100,000 xp difference between when you start the level and finish the level, but it will be 75000/175000 to start.  It is technically correct right now just not what is used to being displayed for this type of thing

**Comment by NecronomiconCoding** [comment]
@Jaerin any tips on fixing ?

**Comment by Brewfasa** [comment]
Isn't it possible to just withdraw the previous level ammount?
Current level = 22, exp (as stated right now ) 75.000/175.000 - level 21 required xp (75.000) = display ammount

**Comment by Jaerin** [comment]
You need to subtract an additional amount of Xp as the difference with the previous level.

Can't seem to get this to work inline in the code:

```
long xpDiff = GetXpDiff(playerstat.PrevLevelXp);

$"Character Level {playerName} {playerStat.Level:0} - ({playerStat.Experience - playerStat.PrevLevelXp:0 - xpDiff} / {playerStat.NextLevelXp - playerStat.PrevLevelXp:0 - xpDiff} XP)";
```

I don't know C# very well, but I believe this logic is sound with the proper syntax
