### ISSUE TITLE
[Suggestion] IVs only

### ISSUE THREAD

**Issue by Hitsuomy** [NecronomiconCoding/Pokemon-Go-Bot#83]
Not sure if it's possible or not, I was looking at the code and I want to only keep the highest IV possible, for example, if I set the IV to 90% I only want the Pokemons with at least that amount to not be transferred, is it possible fixing the transfer only by the IVs?

**Comment by ReddoKiddo** [comment]
It is already like that... it will also keep the highest CP of each pokemon type though... but it will also keep pokemon that has IV higher than minIV

if the pokemon has highest CP and also is the only one in that type who has higher IV than minIV then it will keep only that pokemon

**Comment by joshk6656** [comment]
Right now it is keeping the highest IV possible OR highest CP possible, so technically you could have 2 of each pokemon depending on your settings. 

If you don't care about CP, set the min CP to 10000 and it will only keep the highest IV pokemon.

**Comment by joshk6656** [comment]
TransferDuplicate on, max CP to 10000 and your IV percent to what you want to keep.

**Comment by Hitsuomy** [comment]
Thnks, makes sense setting the CP to 10k
