### ISSUE TITLE
[MINOR] How to display enum differently?

### ISSUE THREAD

**Issue by D4nGuerrero** [NecronomiconCoding/Pokemon-Go-Bot#88]
How can you display, for example: ITEM_POKE_BALL to Poke Ball?

**Comment by gewoon** [comment]
IDK, you could try replacing ITEM_POKE_BALL for Poke Ball before the message is being sent but that doesn't sound like a very good way to do it...

**Comment by D4nGuerrero** [comment]
Yea, for now using:

`var pokeball = await GetBestBall(encounter?.WildPokemon);
                var ball = "ball";
                     if (pokeball == MiscEnums.Item.ITEM_POKE_BALL) { ball = "Poke Ball"; }
                else if (pokeball == MiscEnums.Item.ITEM_POKE_BALL) { ball = "Great Ball"; }
                else if (pokeball == MiscEnums.Item.ITEM_POKE_BALL) { ball = "Ultra Ball"; }
                else if (pokeball == MiscEnums.Item.ITEM_POKE_BALL) { ball = "Master Ball"; }`
