### ISSUE TITLE
Commands for the bot?

### ISSUE THREAD

**Issue by FunctionCode** [NecronomiconCoding/Pokemon-Go-Bot#89]
I'm sort of confused. Are there commands for the bot or does it just do its own thing? Every time I type # the bot closes on itself. Am I doing something wrong?

**Comment by gewoon** [comment]
The bot is automatic (duhh, a bot) You shouldn't press any buttons. This indeed closes the Console.

**Comment by FunctionCode** [comment]
So it farms automatically and goes to pokestops and everything automatically?

**Comment by gewoon** [comment]
Yep it does. If you set the correct locations.
