### ISSUE TITLE
Minor - Visual error in the Console

### ISSUE THREAD

**Issue by makem2203** [NecronomiconCoding/Pokemon-Go-Bot#92]
There are 'extra' spaces after the number of the IV then '%' character

https://images-2.discordapp.net/.eJwVyEEOhCAMAMC_8AAKRQv6G4IEjUoJ1HjY7N83O8f5qKdfalW7SBsrwHaMxH3TQ7jHknVhLleO7Rg68Q1RJKb9zlUGoCFDs0MKSA7d4s2_rHcLWfQWJwpTgKeeld-qWy3q-wMFyyLX.edtVDUy74fcGHjkycfuSxOZxYKE.png

https://images-ext-2.discordapp.net/eyJ1cmwiOiJodHRwczovL2kuZ3lhem8uY29tL3RodW1iLzEyMDAvXzgwNDdhOWYyZTJkMDE0MTg0YWZhMGYwMjMyNGZiMzQwLXBuZy5qcGcifQ.migrv6QzFg9b3Vp5BRtKh3Lgrfc.jpg

**Comment by NecronomiconCoding** [comment]
fixed

**Comment by makem2203** [comment]
Thanks Necro. ;)

It's fixed on everything apart from the 'INFO' list see image: https://gyazo.com/95972ce4b7b39b9cc93438900f0b38e0
