### ISSUE TITLE
1.0.2.2 Log in Error

### ISSUE THREAD

**Issue by ridoknight** [NecronomiconCoding/Pokemon-Go-Bot#94]
![adsiz](https://cloud.githubusercontent.com/assets/20602186/17073156/acb71c4e-5076-11e6-840b-c1eeabe08924.png)

**Comment by Project-HOPS** [comment]
Try rebuilding

**Comment by salvaracer** [comment]
Me too, with Ptc and Google

**Comment by nrmodesto** [comment]
I'm having the same error in the last build...

**Comment by bebar69** [comment]
same issue

**Comment by blackms** [comment]
I'm working on it.

**Comment by Shroomzie** [comment]
Yeah seemed to happen on the skupfer  commits for user settings ect

**Comment by MonsterMMORPG** [comment]
same error here. anyone figured?

**Comment by gewoon** [comment]
Yep same, switching back to the previous version for now.

**Comment by OverlordQ** [comment]
Replacing `_clientSettings` with `_client.Settings` on line 78 of Inventory.cs fixes it as a workaround.
