### ISSUE TITLE
Not automatically farming pokestops around me?

### ISSUE THREAD

**Issue by FunctionCode** [NecronomiconCoding/Pokemon-Go-Bot#95]
I live right next to a pokestop and the bot is not automatically collecting it even tho the lat and long are right on it.

**Comment by salvaracer** [comment]
maybe the bot have saved the last visited coordinates from the last run.

**Comment by FunctionCode** [comment]
Could be right. Is this all the bot is supposed to show me?  http://prntscr.com/bwc07q It is showing nothing else but that every minute or so.

**Comment by Shroomzie** [comment]
"Could be right" No, there might be something wrong. Try changing coordinates to a house up the street or further. That and rebuild.
