### ISSUE TITLE
[Doubt] Does it prioritize CP over IV?

### ISSUE THREAD

**Issue by LasaFawkes** [NecronomiconCoding/Pokemon-Go-Bot#97]
I think I saw the bot transfer a Diglett just because it caught one with higher CP, even though the first one had much higher IVs. Is it supposed to work like that? If so, can it be changed somehow?

**Comment by Brewfasa** [comment]
You have to put the IV you want to keep in the usersettings.. the default is 85% if its below that, it will just transfer it.

**Comment by LasaFawkes** [comment]
Yep, I did that. The problem is both were under that threshold (I set it to 65), but it's supposed to keep one of them regardless of its IV. In my case, it discarded the one with lower IV in favor of the one with higher CP, that's why I'm asking.

**Comment by LasaFawkes** [comment]
I got this just now:
[01:22:48] (TRANSFERED) Sandshrew with 149 (35,00 % perfect) CP (Best: 402 | (23,33 % perfect))

That's what I'm trying to say :)

**Comment by LasaFawkes** [comment]
@NecronomiconCoding You might want to check my previous post out :) Also, do you have any idea why it won't let me send pull requests? I have a few minor misspelling fixes that I would like to share.
