### ISSUE TITLE
'<ERROR> NullReferenceException'

### ISSUE THREAD

**Issue by Biizzle** [NecronomiconCoding/Pokemon-Go-Bot#98]
![untitled](https://cloud.githubusercontent.com/assets/20605208/17073383/51cdd8a8-5068-11e6-8db5-0dd0df94f3b3.png)

Does this whenever I start it up, have I done something wrong? Followed everything on the set up tutorial and changed the latitude and longitude multiple times to different locations..

**Comment by ridoknight** [comment]
Fixed. Update ur api

**Comment by gewoon** [comment]
Update it!
